"use client";

import React from "react";
import { CheckCircle2, User, Video, ShieldCheck, ArrowRight } from "lucide-react";
import { PlatformTheme } from "@/config/service-sales.config";

interface ConfidenceSectionProps {
  platformName: string;
  serviceName: string;
  theme: PlatformTheme;
  socialUsername: string | null;
  targetValue: string | null;
  verifiedTargetData: Record<string, any> | null;
  onScrollToPlans: () => void;
}

export function ConfidenceSection({
  platformName,
  serviceName,
  theme,
  socialUsername,
  targetValue,
  verifiedTargetData,
  onScrollToPlans,
}: ConfidenceSectionProps) {
  const displayHandle = (socialUsername || targetValue || "").replace(/^@+/, "");
  const avatarUrl = verifiedTargetData?.avatar_url || verifiedTargetData?.profile_pic_url || verifiedTargetData?.picture || null;

  return (
    <section className="w-full max-w-5xl mx-auto px-4 py-10 md:py-14">
      <div className="p-6 sm:p-8 md:p-10 rounded-3xl bg-[#0e131f]/80 border border-neutral-800/80 shadow-xl backdrop-blur-md flex flex-col md:flex-row items-center justify-between gap-6 md:gap-8">
        <div className="space-y-2.5 max-w-xl text-center md:text-left">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[10px] font-extrabold uppercase tracking-wider text-blue-400 bg-blue-500/10 border border-blue-500/20">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>BUILT AROUND YOUR TARGET</span>
          </div>

          <h3 className="text-xl sm:text-2xl md:text-3xl font-black text-white tracking-tight">
            Your Order Stays Connected to Your Verified Target.
          </h3>

          <p className="text-xs sm:text-sm text-neutral-400 leading-relaxed">
            Every checkout link generated by CloutFlow is cryptographically mapped to the target you confirmed. No mixed destinations, no password requirements, and zero guesswork.
          </p>
        </div>

        {/* Target Profile Mini Display */}
        <div className="flex flex-col items-center sm:items-end gap-3 shrink-0">
          <div className="flex items-center gap-3 p-3 rounded-2xl bg-[#080b12] border border-neutral-800/90 shadow-md">
            <div className="w-12 h-12 rounded-full overflow-hidden bg-neutral-800 border border-neutral-700 shrink-0 flex items-center justify-center">
              {avatarUrl ? (
                <img src={avatarUrl} alt={displayHandle} className="w-full h-full object-cover" />
              ) : (
                <User className="w-6 h-6 text-neutral-400" />
              )}
            </div>

            <div className="text-left pr-2">
              <div className="flex items-center gap-1">
                <p className="text-xs font-bold text-white truncate max-w-[140px]">
                  {displayHandle ? `@${displayHandle}` : "Verified Target"}
                </p>
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
              </div>
              <p className="text-[10px] text-neutral-400">{platformName} • {serviceName}</p>
              <span className="text-[9px] text-emerald-400 font-semibold block mt-0.5">Ready for dispatch</span>
            </div>
          </div>

          <button
            type="button"
            onClick={onScrollToPlans}
            className="text-xs font-bold text-neutral-300 hover:text-white flex items-center gap-1.5 transition-colors underline cursor-pointer"
          >
            <span>Choose your package above</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </section>
  );
}
